service: telegram-bot

provider:
  name: aws
  stage: dev
  runtime: python3.9
  region: eu-north-1
  memorySize: 128
  timeout: 15
  environment:
    TELEGRAM_TOKEN: ${env:TELEGRAM_TOKEN_DEV}
    ENVIRONMENT: ${self:provider.stage}
functions:
  webhook:
    handler: handler.webhook
    events:
      - httpApi:
          method: POST
          path: /

  set_webhook:
    handler: handler.set_webhook
    events:
      - httpApi:
          method: POST
          path: /set_webhook

plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
    dockerizePip: non-linux
    dockerImage: mlupin/docker-lambda:python3.9-build
    fileName: requirements.txt

package:
  patterns:
    - "!node_modules/**"
    - "!requirements.txt"
    - "!package.json"
    - "!package-lock.json"
    - "!README.md"
